version: '3.7'

services:
  hadoop-hive:
    image: loum/hadoop-hive:3.2.1-3.1.2-1
    container_name: hadoop-hive
    environment:
      OBJECT_STORE_ENDPOINT: http://minio:9000
      AWS_ACCESS_KEY: 05Y2TVZ3T1RQNH7TI89Q
      AWS_SECRET_KEY: 8P2AajiFu+CHo2+3M2pUgWBhtVLaYUXBqBjGZ3wP
    volumes:
      - ../data:/raw-data
    ports:
      - 10000:10000

  # More at https://docs.min.io/docs/minio-docker-quickstart-guide.html
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: 05Y2TVZ3T1RQNH7TI89Q
      MINIO_SECRET_KEY: 8P2AajiFu+CHo2+3M2pUgWBhtVLaYUXBqBjGZ3wP
    ports:
      - 9000:9000
    entrypoint: sh
    command: -c 'mkdir -p /export/raw && mkdir -p /export/hive/dwh && /usr/bin/minio server /export'

  zeppelin:
    image: loum/zeppelin-hive:${HASH}
    build:
      context: ./docker/zeppelin-hive
    container_name: zeppelin
    environment:
      ZEPPELIN_LOG_DIR: /logs
      ZEPPELIN_NOTEBOOK_DIR: /notebook
      ZEPPELIN_ADDR: 0.0.0.0
    volumes:
      - ./docker/zeppelin-hive/notebook:/notebook
      - ./docker/zeppelin-hive/logs:/logs
    ports:
      - 8080:8080
